env:
  global:
    secure: cIGYsPd8OZ3X/ugDZyySmlMl/6gMcMMZQupTgPzHeq24mx+NR7gbVfQmTVnBjmXIpEemQFSe1KwQA2xdvkJ+rhObs8e1tldWFxjXd95Drlf1rKx1oy1LehPmXN4IpbY7PqEbncoSJywb7aLe18u+/2NFA27JsMh83y2xv6YfTQE=

dist: xenial

language: php

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache


matrix:
    include:
        - php: "7.4"
        - php: "7.3"
        - php: "7.2"
        - php: "7.1"
        - php: "7.0"
        - php: "5.6"
        - php: "5.5"
          dist: trusty
        - php: "5.4"
          dist: trusty

before_install:
#  - curl -s https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.4.6/elasticsearch-2.4.6.tar.gz | tar xz -C /tmp
  - wget https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.6.zip -O /tmp/elasticsearch-1.7.6.zip
  - unzip /tmp/elasticsearch-1.7.6.zip -d /tmp/
  - 'echo "script.disable_dynamic: false" | sudo tee -a /tmp/elasticsearch-1.7.6/config/elasticsearch.yml'
#  - 'echo "script.inline: on" | sudo tee -a /tmp/elasticsearch-2.4.6/config/elasticsearch.yml'
#  - 'echo "script.indexed: on" | sudo tee -a /tmp/elasticsearch-2.4.6/config/elasticsearch.yml'
install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction
before_script:
  # - /tmp/elasticsearch-2.4.6/bin/elasticsearch -d
  - /tmp/elasticsearch-1.7.6/bin/elasticsearch -d
  - sleep 20
  - echo 'elasticsearch version ' && curl http://localhost:9200/
  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
    fi
script:
  - vendor/bin/phpunit --verbose $PHPUNIT_FLAGS
after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
